---
deployment:
  tasks:
    - export DEPLOYPATH=/home/codihr/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp webhook.php $DEPLOYPATH
    - /bin/cp favicon.svg $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp cookie-policy.html $DEPLOYPATH
