name: 🚀 Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 📂 Deploy to cPanel via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_path: /home/codihr/public_html/
          local_path: ./*
          sftp_only: true
          args: '-o StrictHostKeyChecking=no'
